# Generated by Django 4.2.3 on 2023-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctions_id_alter_bids_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
