# Generated by Django 4.2.3 on 2023-08-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctions_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Active_Watchers', to='auctions.auctions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_Watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
