# Generated by Django 4.2.3 on 2023-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
