# Generated by Django 4.2.3 on 2023-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctions_winner_alter_auctions_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
